#! /bin/sh
current=$(sed -n -e "s/^linux_fs_start\t\([01]\)$/\1/p" /proc/sys/urlader/environment)
if [ ${#current} -eq 1 ]; then
	new=$(( ( $current + 1 ) % 2 ))
	echo "linux_fs_start $new" >/proc/sys/urlader/environment
	echo "system switched - new value is: linux_fs_start $new" 1>&2
	exit 0
else
	echo "unable to read linux_fs_start value" 1>&2
	exit 1
fi
