#! /bin/bash
host=jws.avm.de
port=80
serial=$1
oem=$2
lang=$3
annex=$4
country=$5
version=$6
revision=$7
hw=$8
name="$9"
nonce=$(dd if=/dev/urandom bs=16 count=1 2>/dev/null | base64)
body="$(echo -n -e "\n<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:soap-enc=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:j=\"http://jason.avm.de/updatecheck/\">\n<soap:Header/>\n<soap:Body>\n<j:BoxFirmwareUpdateCheck>\n<j:RequestHeader>\n<j:Nonce>$nonce</j:Nonce>\n<j:UserAgent>Box</j:UserAgent>\n<j:ManualRequest>true</j:ManualRequest></j:RequestHeader>\n<j:BoxInfo>\n<j:Name>$name</j:Name>\n<j:HW>$hw</j:HW>\n<j:Version>$version</j:Version>\n<j:Revision>$revision</j:Revision>\n<j:Serial>$serial</j:Serial>\n<j:OEM>$oem</j:OEM>\n<j:Lang>$lang</j:Lang>\n<j:Annex>$annex</j:Annex>\n<j:Lab></j:Lab>\n<j:Country>$country</j:Country>\n<j:UpdateConfig>1</j:UpdateConfig></j:BoxInfo></j:BoxFirmwareUpdateCheck></soap:Body></soap:Envelope>")"
len=${#body}
hdr="$(echo -n -e "POST /Jason/UpdateCheck HTTP/1.1\r\nHost: $host:$port\r\nContent-Length: $len\r\nContent-Type: text/xml; charset=\"utf-8\"\r\nSOAPAction: \"http://jason.avm.de/updatecheck/BoxFirmwareUpdateCheck\"")"
exec 3<>/dev/tcp/$host/$port
echo -ne "$hdr\r\n\r\n" >&3
echo -ne "$hdr\r\n\r\n"
echo -ne "$body" >&3
echo -ne "$body\n\n" 
cat <&3 &
cat=$!
sleep 3
kill $cat
echo -ne "\n"
exec 3>&-
