#! /bin/sh
. juischeck.conf
tf=$(mktemp)
/bin/sh ./juisclient $serial $version $public | sed -n -e "\$p" >$tf
found="$(xmllint --xpath "string(//*[local-name()='Found'])" $tf)"
if [ x$found == xtrue ]; then
	echo "New version found : $(xmllint --xpath "string(//*[local-name()='Version'])" $tf)"
	echo "Download URL: $(xmllint --xpath "string(//*[local-name()='DownloadURL'])" $tf)"
	rm $tf
else
	echo "No newer version found - checked against $version ($public)"
	rm $tf
	exit 1
fi
