#! /bin/sh
if [ -z "$1" ]; then
	timeout=0
else
	timeout=$(( $1 + 0 ))
fi
starttime=$(date +%s)
[ $starttime -gt 86400 ] && exit $rc
difftime=$(( starttime + timeout ))
[ $timeout -eq 0 ] && difftime=$(( starttime + 86400 ))
while [ $(date +%s) -lt $difftime ]; do
	if [ $timeout -gt 0 ]; then
		now=$(date +%s)
		waiting=$(( now - starttime ))
		[ $waiting -gt $timeout ] && exit 1
	fi
    sleep 1
done
exit 0