#! /bin/sh
##################################################################################
#
# prepare a (partial) TFFS image containing the TFFS name table
#
##################################################################################
#
# The TFFS name table is an uncompressed file with node ID 0x1FF, containing a
# four byte integer with the FLASH_FS_* value from tffs.h followed by the name as
# C string (terminating NUL character) aligned up the next 4-byte boundary.
# See the kernel sources for a list of numbers or use the "name_table_from_kernel" 
# script to extract the whole table from a running kernel (the format differs 
# slightly).
#
##################################################################################
#
# The name table is expected as file containing the ID and the name as strings,
# the format is the same as produced by the "name_table_from_kernel" script. The
# name table is read from stdin and the binary output data is written to stdout.
#
# The name table is generated in the order of the lines from the input file.
#
##################################################################################
#
# helper functions
#
##################################################################################
source yourfritz_helpers
##################################################################################
#
# fixed identifiers
#
##################################################################################
nametable_id=511
nametable_version=510
##################################################################################
#
# process name table file
#
##################################################################################
out=""
while read id name; do
	hex_id="$(yf_dec2hex $id 4)"
	len=$(( ( ${#name} + 1 + 3 ) & ~3 ))
	hex_name="$(printf "%s" "$name" | yf_bin2hex)"
	fill=$(( len - ${#name} ))
	entry="$hex_id$hex_name"
	while [ $fill -gt 0 ]; do
		entry="${entry}00"
		fill=$(( fill - 1 ))
	done
	out="$out$entry"
done
len=$(( ${#out} / 2 ))
out="$(yf_dec2hex "$nametable_id" 2)$(yf_dec2hex "$len" 2)$out"
yf_hex2bin "$out"
##################################################################################
#
# regular end of script reached
#
##################################################################################
exit 0
