#! /bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
#######################################################################################################
#                                                                                                     #
# add a new startup script to existing content                                                        #
#                                                                                                     #
#######################################################################################################
#                                                                                                     #
# Copyright (C) 2016-2018 P.Hämmerlein (peterpawn@yourfritz.de)                                       #
#                                                                                                     #
# This program is free software; you can redistribute it and/or modify it under the terms of the GNU  #
# General Public License as published by the Free Software Foundation; either version 2 of the        #
# License, or (at your option) any later version.                                                     #
#                                                                                                     #
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without   #
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU      #
# General Public License under http://www.gnu.org/licenses/gpl-2.0.html for more details.             #
#                                                                                                     #
#######################################################################################################
#                                                                                                     #
# The script creates a writable copy of '/etc/init.d/rc.S' and adds the specified script file (called #
# with '/bin/sh') to 'group 9' of startup scripts. It will be started in front of any sourced or      #
# executed scripts of this group ... this should ensure, that the 'exit 0' statement from the former  #
# 'rc.tail.sh' script (which was called by 'S99-tail') will not terminate the execution of 'rc.S',    #
# before the additional script gets started.                                                          #
#                                                                                                     #
#######################################################################################################
#                                                                                                     #
# constants                                                                                           #
#                                                                                                     #
#######################################################################################################
tmpdir="/tmp"
proc="/proc"
scr="$tmpdir/init_rc_replacement"
rcS="/etc/init.d/rc.S"
#######################################################################################################
#                                                                                                     #
# mount some filesystems                                                                              #
#                                                                                                     #
#######################################################################################################
mount -t proc proc /proc
mount -t tmpfs tmpfs /var
mkdir /var/tmp
#######################################################################################################
#                                                                                                     #
# check debug option                                                                                  #
#                                                                                                     #
#######################################################################################################
if [ "$1" = "-d" ] || [ "$1" = "--debug" ]; then
	debug=1
	shift
	exec 2<>$tmpdir/${0##*/}.log
	printf "exit\n# <<<<< debug output of $0 $* >>>>>\n" 1>&2
	set -x
else
	debug=0
fi
#######################################################################################################
#                                                                                                     #
# process parameters                                                                                  #
#                                                                                                     #
#######################################################################################################
new_script="$1"
shift
#######################################################################################################
#                                                                                                     #
# copy the existing script and add our own                                                            #
#                                                                                                     #
#######################################################################################################
cp "$rcS" "$scr"
sed -e "/^if ls.*S/i[ \$gruppe -eq 9 ] && printf \"Starting '%s %s'\\\\n\" $new_script \"$*\" >/dev/console && /bin/sh $new_script $*" -i "$scr"
#######################################################################################################
#                                                                                                     #
# replace the original file                                                                           #
#                                                                                                     #
#######################################################################################################
mount -o bind "$scr" "$rcS"
#######################################################################################################
#                                                                                                     #
# save debug output to TFFS node                                                                      #
#                                                                                                     #
#######################################################################################################
if [ $debug -eq 1 ]; then
	cat "$rcS" 1>&2
	tffs=$(sed -n -e 's|^[ ]*\([0-9]*\) tffs$|\1|p' /proc/devices)
	if [ ${#tffs} -gt 0 ]; then
		tffs_name=$tmpdir/${0##*/}.tffs
		mknod $tffs_name c $tffs 141
		[ -c $tffs_name ] && cat $tffs_name $tmpdir/${0##*/}.log >$tmpdir/${0##*/}.new && cat $tmpdir/${0##*/}.new >$tffs_name
		rm $tffs_name $tmpdir/${0##*/}.new 2>/dev/null
	fi
fi
#######################################################################################################
#                                                                                                     #
# end of script                                                                                       #
#                                                                                                     #
#######################################################################################################
exit 0
